---
- name: Prepare user
  hosts: all
  become: true
  vars_files:
    - vars/wordpress_vault.yml    
  roles:
#    - { role: user, tags: [prepare] }
    - mysql
    - nginx
    - php
    - wordpress
