---
- name: Create User, Group, Directory
  block:
    - name: Create group
      group:
        name: "{{ user.group }}"

    - name: Create user
      user:
        name: "{{ user.login }}"      
        password: "{{ user.password | password_hash('sha512')  }}"
        shell: /bin/bash
        group: "{{ user.group }}"

    - name: Create directory
      file:
        path={{ user.dir }}
          mode=0755
          owner="{{ user.login }}"
          group="{{ user.group }}"
          state=directory

    - name: Copy file to remote host
      copy:
        src: /home/alles/ansible_cm/roles/user/files/test.txt
        dest: "{{ user.dir }}"

- name: Install packages
  package:
    name:
      - htop
      - unzip
    state: latest
